version: '3'
services:
  app:
    container_name: housework-share-app
    image: node:20-bullseye-slim
    ports:
      - 3000:3000
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    tty: true

  api:
    container_name: housework-share-api
    build: 
      context: ./api
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:8
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: housework-share-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Tokyo
    ports:
      - '${FORWARD_DB_PORT:-13307}:3306'
    volumes:
      - wacom_mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: housework-share-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 8081:80 

volumes:
  wacom_mysql_data: {}